version: "3"

services:
  api:
    restart: always
    container_name: chat_room_server
    build: chat_room
    ports:
      - "8083:8080"
    volumes:
      - ./:/api
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080"
    depends_on:
      - db
  client:
    build: ./client
    restart: always
    container_name: chat_room_client
    command: sh -c "yarn install && yarn serve"
    working_dir: /client
    volumes:
      - ./client:/client:cached
    ports:
      - "8084:8080"

  db:
    image: mongo:4.4.6
    restart: always
    env_file:
      - .env
    expose:
      - 27017
    ports:
      - "27019:27017"
    command: mongod --quiet
